[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11", features = ["macros"] }
pretty_assertions = "1.3.0"
tempfile = "3.5.0"
thiserror = "1.0.40"
